name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      # optional: only needed if you want to push to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PERSONAL_TOKEN }}

    - name: Build Docker image
      run: docker build -t flask-docker-app .

    - name: (Optional) Run container to test
      run: |
        docker run -d -p 5000:5000 --name test-container flask-docker-app
        sleep 5
        curl -f http://localhost:5000 || exit 1
        docker stop test-container
        docker rm test-container
    - name: (Optional) Push Docker image to DockerHub
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME}}/flask-docker-app:latest